name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Clean vendor
        run: rm -rf vendor

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --dev

      - name: Dump optimized autoload
        run: composer dump-autoload -o

      - name: Run Linter
        run: php -d error_reporting="E_ALL & ~E_DEPRECATED" vendor/bin/phpcs --standard=PSR12 src

      - name: Run Tests
        run: vendor/bin/phpunit --colors=always

      - name: Run Tests with Coverage
        run: make test-coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ekaterinachmil_php-project-48
            -Dsonar.organization=ekaterinachmil
            -Dsonar.php.coverage.reportPaths=coverage.xml
